--- Generated by h-lua(https://github.com/h-lua/h-lua)

hslk_unit({
    _parent = "Obla",
    Name = "剑圣",
    HP = 10000,
    sides1 = 1,
    dmgplus1 = 10
})

hslk_unit({
    _parent = "hpea",
    Name = "被刀的菜菜",
    HP = 10000,
    abilList = "",
})
