--- Generated by h-lua-sdk(https://github.com/hunzsig-warcraft3/h-lua-sdk)

SETUP = function()
    -- 设定玩家
    hplayer.qty_max = 1 -- 最大玩家数
    hplayer.convert_ratio = 1000000 -- 换算比率，100金 -> 1木

    -- 设定玩家支持的默认命令
    hcmd.conf({ "-gg", "-apm", "-apc", "-d" }, { 1 })

    -- 调试自动去除迷雾
    cj.FogEnable(not DEBUGGING)
    cj.FogMaskEnable(not DEBUGGING)

    -- 设定玩家
    hplayer.qty_max = 1 -- 最大玩家数
    hplayer.convert_ratio = 1000000 -- 换算比率，100金 -> 1木

    -- 设定敌军
    henemy.set("怪物", nil, { 2 }, false)

end
