--- Generated by h-lua(https://github.com/h-lua/h-lua)

local skill = hslk_ability_empty({
    _parent = "ANcl",
    Name = "回避攻击",
    _attr = {
        avoid = "+100",
    }
})

hslk_unit({
    _parent = "Obla",
    Name = "剑圣",
    HP = 10000,
})

hslk_unit({
    _parent = "hpea",
    Name = "被刀的菜菜",
    HP = 10000,
    abilList = "",
    abilList = string.implode(",", { skill._id }),
})
