--- Generated by h-lua-sdk(https://github.com/hunzsig-warcraft3/h-lua-sdk)

hslk_item({
    Name = "物理学圣剑",
    class = "Permanent",
    _attr = _attr({
        attack_green = "+9999"
    })
})