--- Generated by h-lua(https://github.com/h-lua/h-lua)

require "h-lua" -- h-lua库
require "scripts.alias" -- alias h-lua库别称（参考）
require "scripts.setup" -- setup 游戏准备
require "scripts.japi" -- japi
require "scripts.ui" -- UI

-- h-lua main function 主函数入口
-- The game starts here 游戏从main函数开始运行
function main()

    SETUP()
    JAPI()
    UI()

    local idx = {}
    local pool = {}

    for i = 1, bj_MAX_PLAYER_SLOTS do
        local t = table.section(1, 1000)
        pool[i] = table.random(t, #t)
        idx[i] = math.random(1, #pool[i])
    end

    function asyncRand1000()
        local id = 1 + cj.GetPlayerId(cj.GetLocalPlayer())
        local d = pool[id]
        if (d == nil) then
            return 0
        end
        local i = idx[id]
        if (i >= #d) then
            i = 0
        end
        i = i + 1
        idx[id] = i
        return d[i]
    end

    local count = 0
    local min = 9999
    local max = -9999
    hjapi.Refresh("asyncRand", function()
        local a = asyncRand1000()
        if (a < min) then
            min = a
        end
        if (a > max) then
            max = a
        end
        count = count + 1
        print(count, min, max, a)
        if (count >= 1000) then
            hjapi.Refresh("asyncRand", nil)
        end
    end)


end