--- Generated by h-lua-cli(https://github.com/hunzsig-warcraft3/h-lua-sdk)

require "h-lua" -- h-lua库
require "scripts.alias" -- alias h-lua库别称（参考）
require "scripts.setup" -- setup 游戏准备
require "scripts.ui" -- UI
require "scripts.itemInit"
require "scripts.itemAttr"

-- h-lua main function 主函数入口
-- The game starts here 游戏从main函数开始运行
function main()

    SETUP()
    UI()

    print("hello world!")
    echo("你好，世界！")

    hevent.onEsc(hplayer.players[1], function(evtData)
        local it = hitem.create({
            id = hslk.n2i("物理学圣剑"),
            x = 100,
            y = 0,
        })
        itemCream(it)
    end)

    hero = hunit.create({
        whichPlayer = hplayer.players[1],
        id = hslk.n2i("天选勇者"),
        x = 0,
        y = 0,
        isOpenSlot = true,
    })


    hevent.onItemGet(hero, function(evtData)
        local itemData = hcache.get(evtData.triggerItem, "itemData", nil)
        if (itemData == nil) then
            return
        end
        XaddProperty(evtData.triggerUnit, hitem.getId(evtData.triggerItem), itemData.attr, 1)
    end)
    hevent.onItemDrop(hero, function(evtData)
        local itemData = hcache.get(evtData.triggerItem, "itemData", nil)
        if (itemData == nil) then
            return
        end
        XsubProperty(evtData.triggerUnit, hitem.getId(evtData.triggerItem), itemData.attr, 1)
    end)


end