--- Generated by h-lua-cli(https://github.com/hunzsig-warcraft3/h-lua-sdk)

require "h-lua" -- h-lua库
require "scripts.alias" -- alias h-lua库别称（参考）
require "scripts.setup" -- setup 游戏准备
require "scripts.ui" -- UI

-- h-lua main function 主函数入口
-- The game starts here 游戏从main函数开始运行
function main()

    SETUP()
    UI()

    print("hello world!")
    echo("你好，世界！")

    hitem.create({
        id = hslk.n2i("物理学圣剑"),
        x = 100,
        y = 0,
    })

    local u = hunit.create({
        whichPlayer = hplayer.players[1],
        id = hslk.n2i("天选勇者"),
        x = 0,
        y = 0,
        isOpenSlot = true,
    })
    hattr.set(u,30,{attack = "+5"})
    hattr.set(u,20,{knocking_odds = "+50"})

    selectedUnit = {}
    hplayer.forEach(function(enumPlayer, idx)
        hevent.onSelection(enumPlayer,1,function(evtData)
            selectedUnit[idx] = evtData.triggerUnit
        end)
    end)
end