--- Generated by h-lua(https://github.com/h-lua/h-lua)

hslk_unit({
    _parent = "hpea",
    Name = "天选勇者",
})

local it = hslk_item({
    Name = "奖励",
    Art = "ReplaceableTextures\\CommandButtons\\BTNSnazzyScrollGreen.blp",
    Ubertip = "获得一次三选一技能的机会",
    lumbercost = 0,
    goldcost = 0,
    stockMax = 99,
})

hslk_unit({
    _parent = "hvlt",
    Name = "神秘商人",
    abilList = "Abds,Aall,Apit",
    Makeitems = {it._id},
    Sellitems = "",
    Art = "ReplaceableTextures\\CommandButtons\\BTNResStone.blp",
    modelScale = 2,
    scale = 2.20,
    HP = 100,
    spd = 0,
    sight = 500,
    nsight = 500,
    unitSound = "",
    weapsOn = 0,
    race = "human",
    buildingShadow = "",
    uberSplat = ""
})

hslk_unit({
    _parent = "Obla",
    Name = "剑圣",
    HP = 10000,
})