--- Generated by h-lua-sdk(https://github.com/hunzsig-warcraft3/h-lua-sdk)

local skill = hslk_ability({
    Name = "伪八门金锁阵",
    Hotkey = "Q",
    _parent = "ANcl",
    DataA = { 0 },
    EffectArt = "",
    TargetArt = "",
    CasterArt = "",
    Cool = { 10 },
    DataB = { 0 },
    Cost = { 0 },
    DataD = { 0 },
    DataC = { 1 },
    Rng = { 1000 },
    DataF = { "channel" },
    targs = { "enemies" },
    DataE = { 0 },
    _onSkillEffect = _onSkillEffect(function(evtData)
        local trigUnit = evtData.triggerUnit
        local g = hgroup.createByXY(hunit.x(trigUnit), hunit.y(trigUnit), 800, function(filterUnit)
            return his.alive(filterUnit) and his.enemy(filterUnit, trigUnit)
        end)
        if (#g > 0) then
            local u = table.random(g)
            local x, y = hunit.x(u), hunit.y(u)
            local num = {
                { 500, 100 },
                { 100, 500 },
                { 500, 100 },
                { 100, 500 }
            }
            for i = 1, 4 do
                local xy = math.polarProjection(x, y, 310, 90 * i)
                local eff = heffect.toXY("war3mapImported\\ForceGate_Ashenvale.mdx", xy.x, xy.y, 5)
                hjapi.EXEffectMatRotateZ(eff, 90 * i)
                local r = hrect.create(xy.x, xy.y, num[i][1], num[i][2], "666")
                local i = 0
                htime.setInterval(0.5, function(curTimer)
                    i = i + 1
                    if (i >= 10) then
                        hrect.del(r)
                        curTimer.destroy()
                    end
                    local g1 = hgroup.createByRect(r, function(filterUnit)
                        return his.alive(filterUnit) and his.enemy(filterUnit, trigUnit)
                    end)
                    if (#g1 > 0) then
                        hgroup.forEach(g1, function(enumUnit, _)
                            hskill.damage({
                                sourceUnit = trigUnit, --伤害来源(可选)
                                targetUnit = enumUnit, --目标单位
                                damage = 100, --实际伤害
                                damageSrc = CONST_DAMAGE_SRC.skill,
                                damageType = { CONST_DAMAGE_TYPE.electric }
                            })
                        end)
                    end
                    g1 = nil
                end)
            end
        end
    end)
})

hslk_unit({
    _parent = "hpea",
    Name = "天选勇者",
    HP = 10000,
    abilList = string.implode(",",{skill._id}),
    Builds = ""
})