--- Generated by h-lua(https://github.com/h-lua/h-lua)

require "h-lua" -- h-lua库
require "scripts.global"
require "scripts.alias" -- h-lua库别称（参考）
require "scripts.setup" -- 游戏准备
require "scripts.eventReaction" -- 事件反应
require "scripts.damaging" -- 伤害流
require "scripts.ui" -- UI

-- h-lua main function 主函数入口
-- The game starts here 游戏从main函数开始运行
function main()

    SETUP()
    UI()

    print("你好，世界！")
    echo("你好，世界！")
    dump({ "你好，世界！" }, "dump")



    game.hero[1] = hunit.create({
        whichPlayer = hplayer.players[1],
        id = hslk.n2i("剑圣"),
        x = 0,
        y = 0,
        isOpenSlot = true,
    })
    local shop = hunit.create({
        whichPlayer = hplayer.players[1],
        id = hslk.n2i("神秘商人"),
        x = 500,
        y = 500
    })
    --单位购买物品 触发UI
    --注册出售物品事件
    hevent.onItemSell(shop, function(evtData)
        hitem.destroy(evtData.soldItem)
        local p = hunit.getOwner(evtData.buyingUnit)
        local idx = hplayer.index(p)
        game.skillData[idx] = {}
        local itTy = hslk.typeIds({ "skill" })
        for _ = 1, 3 do
            table.insert(game.skillData[idx], table.random(itTy))
        end
        if (p == hplayer.loc()) then
            --设置UI图标 名称 和描述
            for i = 1, 3 do
                local itSlk = hslk.i2v(game.skillData[idx][i], "slk")
                hjapi.DzFrameSetTexture(hjapi.DzFrameFindByName("awar_jn_" .. i, 0), itSlk.Art, 0)
                hjapi.DzFrameSetText(hjapi.DzFrameFindByName("awar_jnname_" .. i, 0), itSlk.Name)
                hjapi.DzFrameSetText(hjapi.DzFrameFindByName("awar_jnsm_" .. i, 0), itSlk.Ubertip)
            end
            hjapi.DzFrameShow(game.awar, true)
        end
    end)
end