--- Generated by h-lua-sdk(https://github.com/hunzsig-warcraft3/h-lua-sdk)
local x = string.gsub("hello world", "(%w+)", "lua")

hslk_item({
    Name = "物理学圣剑",
    class = "Permanent",
    _remarks = x,
    _attr = _attr({
        attack_green = "+100",
        xtras = _xtras({
            {
                on = CONST_EVENT.attack,
                action = "targetUnit.spec.crack_fly",
                odds = 100,
                val = 100,
                distance = 300,
                height = 200,
                during = 0.5,
            }
        })
    })
})

