--- Generated by h-lua-sdk(https://github.com/hunzsig-warcraft3/h-lua-sdk)


local skill = hslk_ability({
    Name = "火球护体",
    Ubertip = hcolor.greenLight("火球护体"),
    Hotkey = "Q",
    _parent = "ANcl",
    DataA = { 0 },
    EffectArt = "",
    TargetArt = "",
    CasterArt = "",
    Cool = { 3 },
    DataB = { 0 },
    Cost = { 0 },
    DataD = { 0 },
    DataC = { 1 },
    Rng = { 1000 },
    DataF = { "channel" },
    targs = { "enemies" },
    DataE = { 0 },
    _onSkillEffect = _onSkillEffect(function(evtData)
        local u = evtData.triggerUnit
        local x = hunit.x(u)
        local y = hunit.y(u)
        local tb = {}
        local j = 0
        for i = 1, 3 do
            tb[i] = cj.AddSpecialEffect("Abilities\\Weapons\\FireBallMissile\\FireBallMissile.mdl",x,y)
            hjapi.EXSetEffectZ(tb[i],100)
        end
        
        htime.setInterval(0.03,function(curTimer)
            j = j + 3
            if (#tb == 0) then
                curTimer.destroy()
                return
            end
            for k, v in ipairs(tb) do
                local eff_xy = math.polarProjection(hunit.x(u),hunit.y(u),200,120 * k + j)
                hjapi.EXSetEffectXY(v,eff_xy.x,eff_xy.y)

                local g = hgroup.createByXY(eff_xy.x,eff_xy.y, 600, function(filterUnit)
                    return his.enemy(u, filterUnit) and his.alive(filterUnit) and hunit.getUserData(filterUnit) ~= 1
                end)
                if (#g > 0) then
                    table.remove(tb, k)
                    k = k - 1
                    cj.DestroyEffect(v)
                    local unit = table.random(g)
                    hunit.setUserData(unit,1,1)
                    hskill.missile({
                        missile = "Abilities\\Weapons\\FireBallMissile\\FireBallMissile.mdl",
                        scale = 1,
                        hover = 150,
                        speed = 1000,
                        sourceUnit = u,
                        targetUnit = unit,
                        startX = eff_xy.x,
                        startY = eff_xy.y,
                        onEnd = function(unit,_,x,y)
                            local g = hgroup.createByXY(x, y, 300, function(filterUnit)
                                return his.enemy(unit, filterUnit) and his.alive(filterUnit)
                            end)
                            hgroup.forEach(g, function(enumUnit, _)
                                hskill.damage({
                                    sourceUnit = unit, --伤害来源(可选)
                                    targetUnit = enumUnit, --目标单位
                                    damage = hattr.get(unit,"str") * 10, --实际伤害
                                    damageSrc = CONST_DAMAGE_SRC.skill,
                                    damageType = { CONST_DAMAGE_TYPE.fire }
                                })
                            end)
                        end
                    })
                end
            end
        end)


    end)
})

hslk_unit({
    _parent = "hpea",
    Name = "天选勇者",
    HP = 10000,
    abilList = string.implode(",", { skill._id }),
    Builds = ""
})

hslk_unit({
    _parent = "Obla",
    Name = "剑人",
    HP = 10000,
    abilList = string.implode(",", { skill._id }),
    _attr  = _attr({
        mana = "+1000"
    })
})