--- Generated by h-lua(https://github.com/h-lua/h-lua)

require "h-lua" -- h-lua库
require "scripts.alias" -- alias h-lua库别称（参考）
require "scripts.setup" -- setup 游戏准备
require "scripts.alert" -- 警示圈
require "scripts.ui" -- UI

-- h-lua main function 主函数入口
-- The game starts here 游戏从main函数开始运行
function main()

    SETUP()
    UI()

    print("hello world!")
    echo("你好，世界！")

    htime.setInterval(0.2, function()
        alertCircleExclamation(math.random(64, 512), math.random(0, 1000), 0, 1, PLAYER_COLOR_RED)
    end)
    htime.setInterval(0.2, function()
        alertCircleX(math.random(64, 512), math.random(0, -1000), 0, 1, PLAYER_COLOR_GREEN)
    end)

end