--- Generated by h-lua-sdk(https://github.com/hunzsig-warcraft3/h-lua-sdk)

hslk_item({
    Name = "物理学圣剑",
    class = "Permanent",
    _attr = _attr({
        attack_green = "+9876",
        e_fire_attack = "+1",
        e_physical_attack = "+1",
        e_magic_attack = "+1",
        e_soil_attack = "+1",
        e_physical = "+5000"
    })
})

hslk_item({
    Name = "奖励",
    lumbercost = 0,
    goldcost = 0,
})