--- Generated by h-lua-sdk(https://github.com/hunzsig-warcraft3/h-lua-sdk)

hslk_unit({
    _parent = "hpea",
    Name = "天选勇者",
    HP = 9999999
})

hslk_unit({
    _parent = "ngme",
    Name = "神秘商人",
    abilList = "Avul,Apit,Aneu",
    Sellitems = "",
    Art = "ReplaceableTextures\\CommandButtons\\BTNResStone.blp",
    modelScale = 2,
    scale = 2.20,
    HP = 100,
    spd = 0,
    sight = 500,
    nsight = 500,
    unitSound = "",
    weapsOn = 0,
    race = "human",
    buildingShadow = "",
    uberSplat = ""
})
