--- Generated by h-lua-cli(https://github.com/hunzsig-warcraft3/h-lua-sdk)

require "h-lua" -- h-lua库
require "scripts.global" -- 全局
require "scripts.alias" -- alias h-lua库别称（参考）
require "scripts.setup" -- setup 游戏准备
require "scripts.ui" -- UI

-- h-lua main function 主函数入口
-- The game starts here 游戏从main函数开始运行
function main()

    SETUP()
    UI()

    hcamera.changeDistance(hplayer.players[1],1000)

    --怪物路径
    for k, v in ipairs(game.pathPoint) do
        for i, p in ipairs(v) do
            local r = hrect.create(p[1], p[2], 175, 175, "rect" .. k .. i)
            hevent.onEnterRect(r,function(evtData)
                local u = evtData.triggerUnit
                if (his.enemyPlayer(u,hplayer.players[1])) then
                    if (i == #v) then
                        --最后区域
                        hunit.del(u)
                    else
                        -- 往前走
                        cj.IssuePointOrderById(
                            u,
                            851986,
                            v[i + 1][1],
                            v[i + 1][2]
                        )
                    end
                end
            end)
        end
    end

    --刷怪
    local i = 0
    htime.setInterval(1,function(curTimer)
        i = i + 1
        if (i >= 10) then
            curTimer.destroy()
            return
        end
        for i = 1, 4 do
            henemy.create({

                id = hslk.n2i("天选勇者"),
                x = game.pathPoint[i][1][1],
                y = game.pathPoint[i][1][2]
            })
        end
    end)
end