--- Generated by h-lua-sdk(https://github.com/hunzsig-warcraft3/h-lua-sdk)


local skill = hslk_ability({
    Name = "伪旋转飞斧",
    Ubertip = hcolor.greenLight("扔出两把飞斧环绕在自己周围"),
    Hotkey = "Q",
    _parent = "ANcl",
    DataA = { 0 },
    EffectArt = "",
    TargetArt = "",
    CasterArt = "",
    Cool = { 10 },
    DataB = { 0 },
    Cost = { 0 },
    DataD = { 0 },
    DataC = { 1 },
    Rng = { 1000 },
    DataF = { "channel" },
    targs = { "enemies" },
    DataE = { 0 },
    _onSkillEffect = _onSkillEffect(function(evtData)
        local u = evtData.triggerUnit
        local x = hunit.x(u)
        local y = hunit.y(u)
        local tempEffectArrow = cj.AddSpecialEffect("Abilities\\Weapons\\GlaiveMissile\\GlaiveMissile.mdl", x,y)
        local i = 0
        htime.setInterval(0.06, function(curTimer)
            i = i + 1
            if (i > 100) then
                curTimer.destroy()
                heffect.del(tempEffectArrow)
                return
            end
            --更新位置
            x = hunit.x(u)
            y = hunit.y(u)
            local xy = math.polarProjection(x, y, 400, 10 * i)
            if (his.borderMap(xy.x, xy.y) == false) then
                hjapi.EXSetEffectXY(tempEffectArrow, xy.x, xy.y)
                local g = hgroup.createByXY(xy.x, xy.y, 200, function(filterUnit)
                    return his.alive(filterUnit) and his.enemy(u, filterUnit)
                end)
                hgroup.forEach(g, function(enumUnit, _)
                    hskill.damage({
                        sourceUnit = u, --伤害来源(可选)
                        targetUnit = enumUnit, --目标单位
                        damage = 100, --实际伤害
                    })
                end)
            end
        end)
    end)
})

hslk_unit({
    _parent = "hpea",
    Name = "天选勇者",
    HP = 10000,
    abilList = string.implode(",", { skill._id }),
    Builds = ""
})

hslk_unit({
    _parent = "Obla",
    Name = "剑人",
    HP = 10000,
    abilList = string.implode(",", { skill._id }),
})