--- Generated by h-lua-sdk(https://github.com/hunzsig-warcraft3/h-lua-sdk)


local skill = hslk_ability({
    Name = "毁灭",
    Ubertip = hcolor.greenLight("刺穿地面，伤害并晕眩经过的目标"),
    Hotkey = "Q",
    _parent = "ANcl",
    DataA = { 0 },
    EffectArt = "",
    TargetArt = "",
    CasterArt = "",
    Cool = { 3 },
    DataB = { 0 },
    Cost = { 0 },
    DataD = { 0 },
    DataC = { 1 },
    Rng = { 1000 },
    DataF = { "channel" },
    targs = { "enemies" },
    DataE = { 0 },
    _onSkillEffect = _onSkillEffect(function(evtData)
        local u = evtData.triggerUnit
        local x = hunit.x(u)
        local y = hunit.y(u)
        local i = 0
        htime.setInterval(0.5,function(curTimer) 
            i = i + 1
            if (i > 5) then
                curTimer.destroy()
                return
            end
            for n = 1, 10 do
                local xy = math.polarProjection(x,y,i * 200,36 * n)
                heffect.toXY("Abilities\\Spells\\Undead\\Impale\\ImpaleHitTarget.mdl", xy.x, xy.y, 0)
                local g = hgroup.createByXY(xy.x, xy.y, 150, function(filterUnit)
                    return his.enemy(u, filterUnit) and his.alive(filterUnit)
                end)
                hgroup.forEach(g, function(enumUnit, _)
                    hskill.crackFly({
                        damage = 100, --伤害（必须有，但是这里可以等于0）
                        targetUnit = enumUnit, --目标单位（必须有）
                        sourceUnit = u, --伤害来源单位（可选）
                        odds = 100, --几率（可选,默认100）
                        distance = 0, --击退距离，可选，默认0
                        height = 200, --击飞高度，可选，默认100
                        during = 0.5, --击飞过程持续时间，可选，默认0.5秒
                    })
                end)
            end
        end)

    end)
})

hslk_unit({
    _parent = "hpea",
    Name = "天选勇者",
    HP = 10000,
    abilList = string.implode(",", { skill._id }),
    Builds = ""
})

hslk_unit({
    _parent = "Obla",
    Name = "剑人",
    HP = 10000,
    abilList = string.implode(",", { skill._id }),
})