--- Generated by h-lua(https://github.com/hunzsig-warcraft3/h-lua)

-- alias 别称
-- 仅供参考，自行调整
hlb = hleaderBoard
hmb = hmultiBoard
hevt = hevent
httg = htextTag
htxt = htexture
hattr = hattribute
hmsg = hmessage