--- Generated by h-lua-cli(https://github.com/hunzsig-warcraft3/h-lua-sdk)

require "h-lua" -- h-lua库
require "scripts.alias" -- alias h-lua库别称（参考）
require "scripts.global"
require "scripts.setup" -- setup 游戏准备
require "scripts.ui" -- UI

-- h-lua main function 主函数入口
-- The game starts here 游戏从main函数开始运行
function main()

    SETUP()
    UI()

    print("hello world!")
    echo("你好，世界！")

    hitem.create({
        id = hslk.n2i("物理学圣剑"),
        x = 100,
        y = 0,
    })

    game.hero[hplayer.players[1]] = hunit.create({
        whichPlayer = hplayer.players[1],
        id = hslk.n2i("天选勇者"),
        x = 0,
        y = 0,
        isOpenSlot = true,
    })
    hevent.onDamage(game.hero[hplayer.players[1]], function(evtData)
        print_mbr(evtData.damageType)
    end)
    hunit.create({
        whichPlayer = hplayer.players[2],
        id = hslk.n2i("天选勇者"),
        x = 0,
        y = 0,
        isOpenSlot = true,
    })
    local shop = hunit.create({
        whichPlayer = hplayer.players[1],
        id = hslk.n2i("神秘商人"),
        x = 500,
        y = 500
    })
    hshop.item.add(shop, hslk.n2i("奖励"), 99)
    --单位购买物品 触发UI
    --注册出售物品事件
    hevent.onItemSell(shop, function(evtData)
        hitem.del(evtData.soldItem)
        local p = hunit.getOwner(evtData.buyingUnit)
        game.skillData[p] = {}
        local itTy = hslk.typeIds({ "skill" })
        for _ = 1, 3 do
            table.insert(game.skillData[p], table.random(itTy))
        end
        if (p == hplayer.loc()) then
            --设置UI图标 名称 和描述
            for i = 1, 3 do
                local itSlk = hslk.i2v(game.skillData[p][i], "slk")
                hjapi.DzFrameSetTexture(hjapi.DzFrameFindByName("awar_jn_" .. i, 0), itSlk.Art, 0)
                hjapi.DzFrameSetText(hjapi.DzFrameFindByName("awar_jnname_" .. i, 0), itSlk.Name)
                hjapi.DzFrameSetText(hjapi.DzFrameFindByName("awar_jnsm_" .. i, 0), itSlk.Ubertip)
            end
            hjapi.DzFrameShow(game.awar, true)
        end
    end)

end