--- Generated by h-lua-sdk(https://github.com/hunzsig-warcraft3/h-lua-sdk)


local skill = hslk_ability({
    Name = "陨石术",
    Hotkey = "Q",
    _parent = "ANcl",
    DataA = { 0 },
    EffectArt = "",
    TargetArt = "",
    CasterArt = "",
    Cool = { 2 },
    DataB = { 2 },
    Cost = { 0 },
    DataD = { 0 },
    DataC = { 1 },
    Rng = { 1000 },
    DataF = { "channel" },
    targs = { "enemies" },
    DataE = { 0 },
    _onSkillEffect = _onSkillEffect(function(evtData)
        local u = evtData.triggerUnit
        local x = hunit.x(u)
        local y = hunit.y(u)
        local ang = hunit.getFacing(u)
        hjapi.EXEffectMatRotateZ(heffect.toXY("war3mapImported\\MeteoriteFalling.mdx",evtData.targetX,evtData.targetY,1.5),ang)
        --延迟1.5秒伤害并滚动
        htime.setTimeout(1.5,function(curTimer)
            curTimer.destroy()
            local g = hgroup.createByXY(x, y, 600, function(filterUnit)
                return his.enemy(u, filterUnit) and his.alive(filterUnit)
            end)
            hgroup.forEach(g, function(enumUnit, _)
                hskill.damage({
                    sourceUnit = u, --伤害来源(可选)
                    targetUnit = enumUnit, --目标单位
                    damage = hattr.get(u,"str") * 10, --实际伤害
                    damageSrc = CONST_DAMAGE_SRC.skill,
                    damageType = { CONST_DAMAGE_TYPE.fire }
                })
            end)
            --滚动
            local xy = math.polarProjection(evtData.targetX,evtData.targetY,1000,ang)
            local onlyOne = {}
            hskill.missile({
                missile = "war3mapImported\\MeteoriteRolling.mdx",
                scale = 1,
                hover = 0,
                speed = 500,
                sourceUnit = u,
                targetX = xy.x,
                targetY = xy.y,
                startX = evtData.targetX, --强制设定初始创建的x坐标（可选的，同时设定 startY 时才有效）
                startY = evtData.targetY, --强制设定初始创建的y坐标（可选的，同时设定 startX 时才有效）
                onMove = function(unit,_, x, y)
                    local g = hgroup.createByXY(x, y, 300, function(filterUnit)
                        return his.enemy(unit, filterUnit) and his.alive(filterUnit)
                    end)
                    hgroup.forEach(g, function(enumUnit, _)
                        --不重复伤害
                        if (onlyOne[enumUnit] == nil) then
                            onlyOne[enumUnit] = 1
                            hskill.damage({
                                sourceUnit = unit, --伤害来源(可选)
                                targetUnit = enumUnit, --目标单位
                                damage = hattr.get(unit,"str") * 10, --实际伤害
                                damageSrc = CONST_DAMAGE_SRC.skill,
                                damageType = { CONST_DAMAGE_TYPE.fire }
                            })
                        end
                    end)
                    g = nil
                    return true
                end
            })
        end)
    end)
})

hslk_unit({
    _parent = "hpea",
    Name = "天选勇者",
    HP = 10000,
    abilList = string.implode(",", { skill._id }),
    Builds = ""
})

hslk_unit({
    _parent = "Obla",
    Name = "剑人",
    HP = 10000,
    abilList = string.implode(",", { skill._id }),
})