--- Generated by h-lua-sdk(https://github.com/hunzsig-warcraft3/h-lua-sdk)

hslk_item({
    Name = "练功秘籍",
    Art = "ReplaceableTextures\\CommandButtons\\BTNManual.blp",
    class = "Permanent",
    _cooldown = 25,
    _attr = _attr({
        attack_green = "+1234",
        life = "+2000",
        life_back = "+50",
        attack_speed = "+150",
    })
})

hslk_hero({
    Name = "天选勇者",
    file = "units\\human\\Footman\\Footman",
    movetp = "foot",
    STRplus = 1,
    AGIplus = 1,
    INTplus = 1,
})

hslk_unit({
    Name = "被刷小怪",
    file = "units\\undead\\Ghoul\\Ghoul"
})