--- Generated by h-lua-sdk(https://github.com/hunzsig-warcraft3/h-lua-sdk)


local skill = hslk_ability({
    Name = "毁灭阴影",
    Ubertip = hcolor.greenLight("毁灭阴影"),
    Hotkey = "Q",
    _parent = "ANcl",
    DataA = { 0 },
    EffectArt = "",
    TargetArt = "",
    CasterArt = "",
    Cool = { 3 },
    DataB = { 0 },
    Cost = { 0 },
    DataD = { 0 },
    DataC = { 1 },
    Rng = { 1000 },
    DataF = { "channel" },
    targs = { "enemies" },
    DataE = { 0 },
    _onSkillEffect = _onSkillEffect(function(evtData)
        local u = evtData.triggerUnit
        local x = hunit.x(u)
        local y = hunit.y(u)
        local ang = hunit.getFacing(u)
        local i = 1
        hunit.pause(u)
        htime.setInterval(0.5,function(curTimer)
            i  = i + 1
            if (i > 4) then
                curTimer.destroy()
                hunit.resume(u)
                return
            end
            local xy = math.polarProjection(x, y, 170 * i, ang)
            hunit.animate(u,"attack")
            hjapi.EXEffectMatScale(
                heffect.toXY("Abilities\\Spells\\Undead\\AnimateDead\\AnimateDeadTarget.mdl",xy.x,xy.y,0),
                2,2,2
            )
            local g = hgroup.createByXY(xy.x, xy.y, 300, function(filterUnit)
                return his.enemy(u, filterUnit) and his.alive(filterUnit)
            end)
            hgroup.forEach(g, function(enumUnit, _)
                hskill.damage({
                    sourceUnit = u, --伤害来源(可选)
                    targetUnit = enumUnit, --目标单位
                    damage = hattr.get(u,"str") * 10, --实际伤害
                    damageSrc = CONST_DAMAGE_SRC.skill,
                    damageType = { CONST_DAMAGE_TYPE.fire }
                })
            end)
        end)
    end)
})

hslk_unit({
    _parent = "hpea",
    Name = "天选勇者",
    HP = 10000,
    abilList = string.implode(",", { skill._id }),
    Builds = ""
})

hslk_unit({
    _parent = "Obla",
    Name = "剑人",
    HP = 10000,
    abilList = string.implode(",", { skill._id }),
})