--- Generated by h-lua(https://github.com/h-lua/h-lua)

local skill = hslk_ability_empty({
    _parent = "ANcl",
    Name = "攻击暴击",
    Ubertip = hcolor.gold("看scripts.damaging|n看scripts.eventReaction"),
    _attr = {
        crit = "+10",
        critOdds = "+50",
    }
})

hslk_unit({
    _parent = "Obla",
    Name = "剑圣",
    HP = 10000,
    abilList = string.implode(",", { skill._id }),
})

hslk_unit({
    _parent = "hpea",
    Name = "天选勇者",
    HP = 10000,
    abilList = "",
})
