--- Generated by h-lua-sdk(https://github.com/hunzsig-warcraft3/h-lua-sdk)


local skill = hslk_ability({
    Name = "火焰风暴",
    Ubertip = hcolor.greenLight("召唤数波火焰风暴对目标区域打击"),
    Hotkey = "Q",
    _parent = "ANcl",
    DataA = { 0 },
    EffectArt = "",
    TargetArt = "",
    CasterArt = "",
    Cool = { 2 },
    DataB = { 2 },
    Cost = { 0 },
    DataD = { 0 },
    DataC = { 3 },
    Rng = { 1000 },
    DataF = { "channel" },
    targs = { "enemies" },
    DataE = { 0 },
    Area = {600},
    _onSkillEffect = _onSkillEffect(function(evtData)
        local u = evtData.triggerUnit
        local i = 0
        htime.setInterval(0.5,function(curTimer)
            i = i + 1
            if (i >= 7) then
                curTimer.destroy()
                return
            end
            for _ = 1, 7 do
                local x = math.random(evtData.targetX - 300,evtData.targetX + 300)
                local y = math.random(evtData.targetY - 300,evtData.targetY + 300)
                hjapi.EXSetEffectSpeed(
                    heffect.toXY("war3mapImported\\RainOfFire.mdx",x,y,0),
                    2
                )
                htime.setTimeout(0.5,function(t)
                    t.destroy()
                    local g = hgroup.createByXY(x, y, 200, function(filterUnit)
                        return his.enemy(u, filterUnit) and his.alive(filterUnit)
                    end)
                    hgroup.forEach(g, function(enumUnit, _)
                        hskill.damage({
                            sourceUnit = u, --伤害来源(可选)
                            targetUnit = enumUnit, --目标单位
                            damage = hattr.get(u,"str") * 10, --实际伤害
                            damageSrc = CONST_DAMAGE_SRC.skill,
                            damageType = { CONST_DAMAGE_TYPE.fire }
                        })
                    end)
                end)
            end
        end)

    end)
})

hslk_unit({
    _parent = "hpea",
    Name = "天选勇者",
    HP = 10000,
    abilList = string.implode(",", { skill._id }),
    Builds = ""
})

hslk_unit({
    _parent = "Obla",
    Name = "剑人",
    HP = 10000,
    abilList = string.implode(",", { skill._id }),
})