--- Generated by h-lua-sdk(https://github.com/hunzsig-warcraft3/h-lua-sdk)

local skill = hslk_ability({
    Name = "无敌斩",
    Hotkey = "Q",
    _parent = "ANcl",
    DataA = { 0 },
    EffectArt = "",
    TargetArt = "",
    CasterArt = "",
    Cool = { 2 },
    DataB = { 1 },
    Cost = { 0 },
    DataD = { 0 },
    DataC = { 1 },
    Rng = { 1000 },
    DataF = { "channel" },
    targs = { "enemies" },
    DataE = { 0 },
    _onSkillEffect = _onSkillEffect(function(evtData)
        WUDIZHAN({
            sourceUnit = evtData.triggerUnit, --伤害来源（必须有！不管有没有伤害）
            targetUnit = evtData.targetUnit, --冲击的目标单位（必须有）
            qty = 10, --（跳跃次数，默认1）
            radius = 1000, --（选目标半径范围，默认0无效）
            speed = 60, --冲击的速度（可选的，默认10，0.02秒的移动距离,大概1秒500px)
            filter = function(unit)
                return his.enemy(evtData.triggerUnit, unit) and his.alive(unit)
            end,
            effectMovement = "Abilities\\Weapons\\PhoenixMissile\\Phoenix_Missile_mini.mdl", --移动过程，每个间距的特效（可选的，采用的0秒删除法，请使用explode类型的特效）
            damageEnd = 100, --移动结束时对目标的伤害（可选的，默认为0）
        })
    end)
})

hslk_unit({
    _parent = "hpea",
    Name = "天选勇者",
    HP = 10000,
    abilList = string.implode(",", { skill._id }),
    Builds = ""
})

hslk_unit({
    _parent = "Obla",
    Name = "剑人",
    HP = 10000,
    abilList = string.implode(",", { skill._id }),
})