--- Generated by h-lua-sdk(https://github.com/hunzsig-warcraft3/h-lua-sdk)

SETUP = function()
    -- 设定玩家
    hplayer.qty_max = 4 -- 最大玩家数
    hplayer.convert_ratio = 1000000 -- 换算比率，100金 -> 1木

    -- 调试自动去除迷雾
    cj.FogEnable(not DEBUGGING)
    cj.FogMaskEnable(not DEBUGGING)


    -- 设定敌军
    henemy.set("怪物", nil, { 6 }, false)

end
