--- Generated by h-lua(https://github.com/h-lua/h-lua)

require "h-lua" -- h-lua库
require "scripts.alias" -- alias h-lua库别称（参考）
require "scripts.setup" -- setup 游戏准备
require "scripts.ui" -- UI

-- h-lua main function 主函数入口
-- The game starts here 游戏从main函数开始运行
function main()

    SETUP()
    UI()

    local a = { a = 1 }
    print(isArray(a))

    local arr = Array()
    print(isArray(arr))
    arr.set("c", 1)
    arr.set("b", 2)
    arr.set("a", 3)
    print(" - keys - ")
    dump(arr.keys())
    print(" - values - ")
    dump(arr.values())
    print(" - forEach - ")
    arr.forEach(function(key, value)
        print(key, value)
    end)
    print(" - backEach - ")
    arr.backEach(function(key, value)
        print(key, value)
    end)
    arr.sort()
    print(" - sort - ")
    arr.forEach(function(key, value)
        print(key, value)
    end)
    print(" - clear b - ")
    arr.set("b", nil)
    arr.forEach(function(key, value)
        print(key, value)
    end)

end