--- Generated by h-lua-sdk(https://github.com/hunzsig-warcraft3/h-lua-sdk)

SETUP = function()
    -- 设定玩家
    hplayer.qty_max = 1 -- 最大玩家数
    hplayer.convert_ratio = 1000000 -- 换算比率，100金 -> 1木

    -- 设定玩家支持的默认命令
    hcmd.conf({ "-gg", "-apm", "-apc", "-d" }, { 1 })

    -- 调试自动去除迷雾
    henv.setFogStatus(DEBUGGING == false, DEBUGGING == false)

    -- 设定玩家
    hplayer.qty_max = 1 -- 最大玩家数
    hplayer.convert_ratio = 1000000 -- 换算比率，100金 -> 1木

    -- 设定敌军
    henemy.set("怪物", nil, { 2 }, false)

    --- 设定获得黄金木头特效
    hevent.onPlayerResourceChange(function(evtData)
        if (evtData.triggerUnit ~= nil and evtData.value > 0) then
            local u = evtData.triggerUnit
            local val = math.floor(evtData.value)
            if (evtData.type == 'gold') then
                htextTag.model({ msg = "+" .. val .. "金", whichUnit = u, red = 255, green = 215, blue = 0 })
                hsound.voice2Unit(cg.gg_snd_ReceiveGold, 100, u)
            elseif (evtData.type == 'lumber') then
                htextTag.model({ msg = "+" .. val .. "木", whichUnit = u, red = 34, green = 139, blue = 34 })
                hsound.voice2Unit(cg.gg_snd_BundleOfLumber, 100, u)
            end
        end
    end)


    BUFF_DISPLAY_KEYS = {}
    --buff图标
    BUFF_ICON = {
        --以下全是附魔相关图标，没弄
        e_physical_attack = "buffIcon\\buff_e_physical_attack.tga",
        e_magic_attack = "buffIcon\\buff_reborn.tga",
        e_fire_attack = "buffIcon\\buff_reborn.tga",
        e_flame_attack = "buffIcon\\buff_reborn.tga",
        e_soil_attack = "buffIcon\\buff_reborn.tga",
        e_rock_attack = "buffIcon\\buff_reborn.tga",
        e_sand_attack = "buffIcon\\buff_reborn.tga",
        e_lava_attack = "buffIcon\\buff_reborn.tga",
        e_water_attack = "buffIcon\\buff_reborn.tga",
        e_ice_attack = "buffIcon\\buff_reborn.tga",
        e_storm_attack = "buffIcon\\buff_reborn.tga",
        e_wind_attack = "buffIcon\\buff_reborn.tga",
        e_light_attack = "buffIcon\\buff_reborn.tga",
        e_dark_attack = "buffIcon\\buff_reborn.tga",
        e_wood_attack = "buffIcon\\buff_reborn.tga",
        e_grass_attack = "buffIcon\\buff_reborn.tga",
        e_thunder_attack = "buffIcon\\buff_reborn.tga",
        e_electric_attack = "buffIcon\\buff_reborn.tga",
        e_metal_attack = "buffIcon\\buff_reborn.tga",
        e_iron_attack = "buffIcon\\buff_reborn.tga",
        e_steel_attack = "buffIcon\\buff_reborn.tga",
        e_dragon_attack = "buffIcon\\buff_reborn.tga",
        e_insect_attack = "buffIcon\\buff_reborn.tga",
        e_poison_attack = "buffIcon\\buff_reborn.tga",
        e_evil_attack = "buffIcon\\buff_reborn.tga",
        e_ghost_attack = "buffIcon\\buff_reborn.tga",
        e_god_attack = "buffIcon\\buff_reborn.tga",
        e_holy_attack = "buffIcon\\buff_reborn.tga",
        e_physical_append = "buffIcon\\buff_reborn.tga",
        e_magic_append = "buffIcon\\buff_reborn.tga",
        e_fire_append = "buffIcon\\buff_reborn.tga",
        e_flame_append = "buffIcon\\buff_reborn.tga",
        e_soil_append = "buffIcon\\buff_reborn.tga",
        e_rock_append = "buffIcon\\buff_reborn.tga",
        e_sand_append = "buffIcon\\buff_reborn.tga",
        e_lava_append = "buffIcon\\buff_reborn.tga",
        e_water_append = "buffIcon\\buff_reborn.tga",
        e_ice_append = "buffIcon\\buff_reborn.tga",
        e_storm_append = "buffIcon\\buff_reborn.tga",
        e_light_append = "buffIcon\\buff_reborn.tga",
        e_dark_append = "buffIcon\\buff_reborn.tga",
        e_wood_append = "buffIcon\\buff_reborn.tga",
        e_grass_append = "buffIcon\\buff_reborn.tga",
        e_thunder_append = "buffIcon\\buff_reborn.tga",
        e_electric_append = "buffIcon\\buff_reborn.tga",
        e_metal_append = "buffIcon\\buff_reborn.tga",
        e_iron_append = "buffIcon\\buff_reborn.tga",
        e_steel_append = "buffIcon\\buff_reborn.tga",
        e_dragon_append = "buffIcon\\buff_reborn.tga",
        e_insect_append = "buffIcon\\buff_reborn.tga",
        e_poison_append = "buffIcon\\buff_reborn.tga",
        e_evil_append = "buffIcon\\buff_reborn.tga",
        e_ghost_append = "buffIcon\\buff_reborn.tga",
        e_god_append = "buffIcon\\buff_reborn.tga",
        e_holy_append = "buffIcon\\buff_reborn.tga",
        e_physical = "buffIcon\\buff_reborn.tga",
        e_physical_oppose = "buffIcon\\buff_reborn.tga",
        e_magic = "buffIcon\\buff_reborn.tga",
        e_magic_oppose = "buffIcon\\buff_reborn.tga",
        e_fire = "buffIcon\\buff_reborn.tga",
        e_fire_oppose = "buffIcon\\buff_reborn.tga",
        e_flame = "buffIcon\\buff_reborn.tga",
        e_flame_oppose = "buffIcon\\buff_reborn.tga",
        e_soil = "buffIcon\\buff_reborn.tga",
        e_soil_oppose = "buffIcon\\buff_reborn.tga",
        e_rock = "buffIcon\\buff_reborn.tga",
        e_rock_oppose = "buffIcon\\buff_reborn.tga",
        e_sand = "buffIcon\\buff_reborn.tga",
        e_sand_oppose = "buffIcon\\buff_reborn.tga",
        e_lava = "buffIcon\\buff_reborn.tga",
        e_lava_oppose = "buffIcon\\buff_reborn.tga",
        e_water = "buffIcon\\buff_reborn.tga",
        e_water_oppose = "buffIcon\\buff_reborn.tga",
        e_ice = "buffIcon\\buff_reborn.tga",
        e_ice_oppose = "buffIcon\\buff_reborn.tga",
        e_storm = "buffIcon\\buff_reborn.tga",
        e_storm_oppose = "buffIcon\\buff_reborn.tga",
        e_wind = "buffIcon\\buff_reborn.tga",
        e_wind_oppose = "buffIcon\\buff_reborn.tga",
        e_light = "buffIcon\\buff_reborn.tga",
        e_light_oppose = "buffIcon\\buff_reborn.tga",
        e_dark = "buffIcon\\buff_reborn.tga",
        e_dark_oppose = "buffIcon\\buff_reborn.tga",
        e_wood = "buffIcon\\buff_reborn.tga",
        e_wood_oppose = "buffIcon\\buff_reborn.tga",
        e_grass = "buffIcon\\buff_reborn.tga",
        e_grass_oppose = "buffIcon\\buff_reborn.tga",
        e_thunder = "buffIcon\\buff_reborn.tga",
        e_thunder_oppose = "buffIcon\\buff_reborn.tga",
        e_electric = "buffIcon\\buff_reborn.tga",
        e_electric_oppose = "buffIcon\\buff_reborn.tga",
        e_metal = "buffIcon\\buff_reborn.tga",
        e_metal_oppose = "buffIcon\\buff_reborn.tga",
        e_iron = "buffIcon\\buff_reborn.tga",
        e_iron_oppose = "buffIcon\\buff_reborn.tga",
        e_steel = "buffIcon\\buff_reborn.tga",
        e_steel_oppose = "buffIcon\\buff_reborn.tga",
        e_dragon = "buffIcon\\buff_reborn.tga",
        e_dragon_oppose = "buffIcon\\buff_reborn.tga",
        e_insect = "buffIcon\\buff_reborn.tga",
        e_insect_oppose = "buffIcon\\buff_reborn.tga",
        e_poison = "buffIcon\\buff_reborn.tga",
        e_poison_oppose = "buffIcon\\buff_reborn.tga",
        e_evil = "buffIcon\\buff_reborn.tga",
        e_evil_oppose = "buffIcon\\buff_reborn.tga",
        e_ghost = "buffIcon\\buff_reborn.tga",
        e_ghost_oppose = "buffIcon\\buff_reborn.tga",
        e_god = "buffIcon\\buff_reborn.tga",
        e_god_oppose = "buffIcon\\buff_reborn.tga",
        e_holy = "buffIcon\\buff_reborn.tga",
        e_holy_oppose = "buffIcon\\buff_reborn.tga",
        --以上全是附魔相关图标，没弄


        reborn = "buffIcon\\buff_reborn.tga",
        attack_speed = "buffIcon\\buff_attack_speed.tga",
        attack_space = "buffIcon\\buff_attack_speed.tga",
        attack_space_origin = "buffIcon\\buff_attack_speed.tga",
        attack = "buffIcon\\buff_attack.tga",
        attack_white = "buffIcon\\buff_attack.tga",
        attack_green = "buffIcon\\buff_attack.tga",
        attack_range_acquire = "buffIcon\\buff_attack_range_acquire.tga",
        attack_range = "buffIcon\\buff_attack_range_acquire.tga",
        defend = "buffIcon\\buff_defend.tga",
        defend_white = "buffIcon\\buff_defend.tga",
        defend_green = "buffIcon\\buff_defend.tga",
        str = "buffIcon\\buff_str.tga",
        agi = "buffIcon\\buff_agi.tga",
        int = "buffIcon\\buff_int.tga",
        str_green = "buffIcon\\buff_str.tga",
        agi_green = "buffIcon\\buff_agi.tga",
        int_green = "buffIcon\\buff_int.tga",
        str_white = "buffIcon\\buff_str.tga",
        agi_white = "buffIcon\\buff_agi.tga",
        int_white = "buffIcon\\buff_int.tga",
        life = "buffIcon\\buff_life.tga",
        mana = "buffIcon\\buff_mana.tga",
        life_back = "buffIcon\\buff_life_back.tga",
        mana_back = "buffIcon\\buff_mana_back.tga",
        move = "buffIcon\\buff_move.tga",
        sight = "buffIcon\\buff_sight.tga",
        avoid = "buffIcon\\buff_avoid.tga",
        aim = "buffIcon\\buff_aim.tga",
        punish = "buffIcon\\buff_punish.tga",
        punish_current = "buffIcon\\buff_punish.tga",
        hemophagia = "buffIcon\\buff_hemophagia.tga",
        hemophagia_skill = "buffIcon\\buff_hemophagia.tga",
        siphon = "buffIcon\\buff_siphon.tga",
        siphon_skill = "buffIcon\\buff_siphon.tga",
        invincible = "buffIcon\\buff_invincible.tga",
        weight = "buffIcon\\buff_weight.tga",
        weight_current = "buffIcon\\buff_weight.tga",
        damage_extent = "buffIcon\\buff_damage_extent.tga",
        damage_reduction = "buffIcon\\buff_damage_reduction.tga",
        damage_decrease = "buffIcon\\buff_damage_reduction.tga",
        damage_rebound = "buffIcon\\buff_damage_rebound.tga",
        damage_rebound_oppose = "buffIcon\\buff_damage_rebound.tga",
        cure = "buffIcon\\buff_cure.tga",
        knocking_odds = "buffIcon\\buff_knocking_odds.tga",
        knocking_extent = "buffIcon\\buff_knocking_extent.tga",
        knocking_oppose = "buffIcon\\buff_knocking_oppose.tga",
        hemophagia_oppose = "buffIcon\\buff_hemophagia_oppose.tga",
        hemophagia_skill_oppose = "buffIcon\\buff_hemophagia_oppose.tga",
        siphon_oppose = "buffIcon\\buff_hemophagia_oppose.tga",
        siphon_skill_oppose = "buffIcon\\buff_hemophagia_oppose.tga",
        split_oppose = "buffIcon\\buff_split_oppose.tga",
        punish_oppose = "buffIcon\\buff_punish_oppose.tga",
        swim_oppose = "buffIcon\\buff_swim_oppose.tga",
        broken_oppose = "buffIcon\\buff_broken_oppose.tga",
        silent_oppose = "buffIcon\\buff_silent_oppose.tga",
        unarm_oppose = "buffIcon\\buff_unarm_oppose.tga",
        fetter_oppose = "buffIcon\\buff_fetter_oppose.tga",
        bomb_oppose = "buffIcon\\buff_bomb_oppose.tga",
        lightning_chain_oppose = "buffIcon\\buff_lightning_chain_oppose.tga",
        crack_fly_oppose = "buffIcon\\buff_crack_fly_oppose.tga",
        xtras = "ReplaceableTextures\\PassiveButtons\\PASBTNBash.blp",
        gold_ratio = "buffIcon\\buff_gold_ratio.tga",
        lumber_ratio = "buffIcon\\buff_lumber_ratio.tga",
        exp_ratio = "buffIcon\\buff_exp_ratio.tga",
        sell_ratio = "buffIcon\\buff_sell_ratio.tga",
    }
    for _, k in ipairs(CONST_ATTR_KEYS) do
        table.insert(BUFF_DISPLAY_KEYS, { name = CONST_ATTR[k], icon = BUFF_ICON[k] })
    end

end
