--- Generated by h-lua(https://github.com/h-lua/h-lua)

local ab = hslk_ability({
    _parent = "Aro2",
    Name = "新扎根",
    Buttonpos_1 = 0,
    Buttonpos_2 = -11,
    --UnButtonpos_1 = 0, -- 可隐藏不删除
    --UnButtonpos_2 = -11,
    DataA = { 3 },
    DataC = { 1 },
})._id

hslk_unit({
    _parent = "hgtw",
    Name = "天选勇者",
    weapTp1 = "missile",
    cool1 = 0.5,
    dmgplus1 = 100,
    rangeN1 = 1000,
    file = "units\\orc\\HeroTaurenChieftain\\HeroTaurenChieftain",
    Missileart_1 = "Abilities\\Spells\\Orc\\Shockwave\\ShockwaveMissile.mdl",
    abilList = ab,
    upgrades = "",
    Requires = "",
    movetp = "foot",
    spd = 1,
    turnRate = 3.0,
})

hslk_unit({
    Name = "受苦之民",
    abilList = "",
    Builds = ""
})