--- Generated by h-lua-cli(https://github.com/hunzsig-warcraft3/h-lua-sdk)

require "h-lua" -- h-lua库
require "scripts.alias" -- alias h-lua库别称（参考）
require "scripts.setup" -- setup 游戏准备
require "scripts.ui" -- UI

require "scripts.example.ItemLevel"
require "scripts.example.framePoint"
require "scripts.example.diyui"

-- h-lua main function 主函数入口
-- The game starts here 游戏从main函数开始运行
function main()
    
    SETUP()
    UI()

    print("hello world!")
    echo("你好，世界！")
        
    
    local u =hunit.create({
        whichPlayer = hplayer.players[1],
        id = hslk.n2i("天选勇者"),
        x = 0,
        y = 0,
        isOpenSlot = true,
    })

    local i1 = hitem.create({
        id = hslk.n2i("物理学圣剑"),
        x = 100,
        y = 0,
    })

    local i2 = hitem.create({
        id = hslk.n2i("物理学圣剑"),
        x = 100,
        y = 0,
    })

    
    -- 坐标轴演示
    -- Coord()     
    -- 相对定位演示
    -- FramePont() 

    -- UI封装演示
    TestUi()

    -- 强化物品
    -- ItemLevelUp(i1,i2,u);

    -- 刷怪
    -- rectCreatEnemy(hslk.n2i("小怪"),10,3);

end


-- 物品强化属性 
function ItemLevelUp(i1,i2,u)
    -- 注册物品等级
    ItemLevel[i1] = {level = 1}
    ItemLevel[i2] = {level = 1}
    -- 注册物品强化附加属性
    ItemAttr[hslk.n2i("物理学圣剑")] = {
        -- 强化附加属性1级,2级,3级
        levelAttr = {
            {
                life = "+0",
                attack_green = "+0",
            },
            {
                life = "+20",
                attack_green = "+200",
            },
            {
                life = "+30",
                attack_green = "+300",
            },
            {
                life = "+40",
                attack_green = "+400",
            },
            {
                life = "+50",
                attack_green = "+500",
            }, 
            {
                life = "+60",
                attack_green = "+600",
            }
        },
        -- 套装附加属性
        setAttr = {
        }
    }
    -- 强化按钮
    ItemCall.levelBtn(u);
end

-- 区域刷怪
function rectCreatEnemy(enemyId,maxNum,minNum)
    local maxNum = maxNum or 5;
    local minNum = minNum or 0;
    local currentNum =  0;

    function deadCall(evtData) 
        hunit.del(evtData.triggerUnit)
        currentNum = currentNum - 1;
        if(currentNum <= minNum) then
            creatEnemy();
        end
    end
    function creatEnemy()
        for i = 1, maxNum - currentNum do
            local u = henemy.create({
                id = enemyId,
                x = 30,
                y = 30,
            })
            hevent.onDead(u,deadCall)
        end
        currentNum = maxNum;
    end
    creatEnemy()
end