--- Generated by h-lua-sdk(https://github.com/h-lua/h-lua)

hslk_hero({
    Name = "天选勇者",
    file = "units\\human\\Footman\\Footman",
    movetp = "foot",
    STRplus = 1,
    AGIplus = 1,
    INTplus = 1,
})

hslk_unit({
    Name = "被电小怪",
    file = "units\\undead\\Ghoul\\Ghoul"
})