--- Generated by h-lua(https://github.com/h-lua/h-lua)
local x = string.gsub("hello world", "(%w+)", "lua")

hslk_item({
    Name = "物理学圣剑",
    class = "Permanent",
    _remarks = x,
    _attr = _attr({
        attack_green = "+100",
    })
})

