--- Generated by h-lua(https://github.com/hunzsig-warcraft3/h-lua)

require "h-lua" -- h-lua库
require "scripts.alias" -- alias h-lua库别称（参考）
require "scripts.setup" -- setup 游戏准备
require "scripts.sound" -- 声音
require "scripts.ui" -- UI

-- 加载本地图的设置
require "scripts.setting.global"
require "scripts.setting.dz"
-- 设定友军
game.ALLY_PLAYER = hplayer.players[12]
require "scripts.setting.f9"
require "scripts.setting.quest"
-- stage
require "scripts.stages.common"
require "scripts.stages.stage1"
require "scripts.stages.stage2"
require "scripts.stages.stage3"
require "scripts.stages.stage4"
require "scripts.stages.stage5"
require "scripts.stages.stage6"
require "scripts.stages.stage7"
require "scripts.stages.stage8"
require "scripts.stages.stage9"

-- h-lua main function 主函数入口
-- The game starts here 游戏从main函数开始运行
function main()

    UI()

    hsound.bgmStop()
    hsound.bgm(SOUND.bgm_main)

    -- hello
    echo("^_^ 您来到了秘境，请选择" .. hcolor.yellow("你的英雄"))
    -- 玩家配置
    for i = 1, hplayer.qty_max, 1 do
        if (his.playing(hplayer.players[i])) then
            -- 称号
            hplayer.setPrestige(hplayer.players[i], "冒险者")
            dzCurrent.enableRecord(hplayer.players[i])
        end
    end

    -- 第 1 玩家选择模式
    echo("第1位玩家正在选择难度", nil, 10)
    hdialog.create(
        nil,
        {
            title = "选择难度",
            buttons = {
                "一般困难",
                "非常困难",
                "极其困难",
                "破天荒难",
            }
        },
        function(btnIdx)
            local diff = 1
            local diffColor = hcolor.yellowLight
            local rebornQty = 20
            if (btnIdx == "非常困难") then
                diff = 5
                diffColor = hcolor.yellow
                rebornQty = 10
            elseif (btnIdx == "极其困难") then
                diff = 20
                diffColor = hcolor.redLight
                rebornQty = 3
            elseif (btnIdx == "破天荒难") then
                diff = 50
                diffColor = hcolor.red
                rebornQty = 1
            end
            game.diff = diff
            game.rebornQty = hplayer.qty_current * rebornQty
            echo("选择了：" .. diffColor(btnIdx) .. ",全体复活次数有：" .. hcolor.green(game.rebornQty) .. "次")
            --- 英雄选择
            hhero.setBornXY(-7044, -8965)
            --- 酒馆商店
            hhero.buildSelector({
                during = 60,
                type = "tavern",
                buildX = -8704, -- 构建点X
                buildY = -9216, -- 构建点Y
                buildDistance = 256,
                direct = { 1, -1 },
                buildRowQty = 4,
                tavernUnitQty = 12
            })
            stage1()
        end
    )
end