--- Generated by h-lua(https://github.com/h-lua/h-lua)

require "h-lua" -- h-lua库
require "scripts.alias" -- alias h-lua库别称（参考）
require "scripts.setup" -- setup 游戏准备
require "scripts.buff" -- buff
require "scripts.buffUI" -- buff - ui
require "scripts.ui" -- UI

-- h-lua main function 主函数入口
-- The game starts here 游戏从main函数开始运行
function main()

    SETUP()
    UI()

    echo("这个演示是很旧的演示，以老版本的buff库作为设计")
    echo("可自行拓展或大改，增加自定义描述，丰富buff的功能")

    hitem.create({
        id = hslk.n2i("物理学圣剑"),
        x = 100,
        y = 0,
    })

    local u = hunit.create({
        whichPlayer = hplayer.players[1],
        id = hslk.n2i("剑圣"),
        x = 0,
        y = 0,
        isOpenSlot = true,
    })

    htime.setInterval(1, function(curTimer)
        local attr = table.random({ "attack", "defend", "str", "agi" }, 1)
        local diff = math.random(-10, 50)
        local diffSet = tostring(diff)
        if (diff > 0) then
            diffSet = "+" .. diffSet
        end
        hbuff.create(
            12, u, attr, diff,
            function()
                hattr.set(u, 0, { [attr] = diffSet })
            end,
            function()
                hattr.set(u, 0, { [attr] = diffSet })
            end
        )
    end)

end