hslk_unit({
    _parent = "ngme",
    Name = "小神木商店",
    abilList = "Avul,Apit,Aneu",
    file = "buildings\\nightelf\\ChimaeraRoost\\ChimaeraRoost",
    Art = "ReplaceableTextures\\CommandButtons\\BTNResStone.blp",
    modelScale = 0.70,
    scale = 2.20,
    HP = 100,
    spd = 0,
    sight = 500,
    nsight = 500,
    unitSound = "",
    weapsOn = 0,
    race = "human",
})