hslk_unit({
    Name = "孤单的火窖",
    abilList = "",
    file = "Doodads\\Northrend\\Props\\FirePit\\FirePit",
    Art = "ReplaceableTextures\\CommandButtons\\BTNResStone.blp",
    modelScale = 1.20,
    scale = 1.30,
    HP = 1000,
    spd = 0,
    sight = 700,
    nsight = 700,
    unitSound = "",
    weapsOn = 0,
    race = "human",
    goldcost = 0,
    lumbercost = 0,
    fmade = 0,
    fused = 0,
})