--- Generated by h-lua(https://github.com/h-lua/h-lua)

local skill = hslk_ability({
    _parent = "ANcl",
    Name = "威远大炮",
    Ubertip = hcolor.greenLight("威远大炮，千里之外，越远越强"),
    Hotkey = "Q",
    DataA = { 0 },
    EffectArt = "",
    TargetArt = "",
    CasterArt = "",
    Cool = { 3 },
    DataB = { 1 },
    Cost = { 0 },
    DataD = { 0 },
    DataC = { 1 },
    Rng = { 5000 },
    DataF = { "channel" },
    targs = { "enemies" },
    DataE = { 0 },
})

hslk_unit({
    _parent = "Obla",
    Name = "剑圣",
    HP = 10000,
    abilList = string.implode(",", { skill._id }),
})

hslk_unit({
    _parent = "hpea",
    Name = "被炮的菜菜",
    HP = 10000,
    abilList = "",
    Builds = ""
})