--- Generated by h-lua-sdk(https://github.com/hunzsig-warcraft3/h-lua-sdk)
ATTR_CONFIGURATOR({
    {"diy_a","自定义属性",20},
    {"weapon_level","强化等级",0}
})

hslk_item({
    Name = "物理学圣剑",
    class = "Permanent",
    _onItemGet = function(evtData)
        local u = evtData.triggerUnit
        local oldAttack = hattribute.get(u,"attack_white")
        local oldAddAttack = hattribute.get(u,"attackAdd1",0)
        local realAttack = oldAttack - oldAddAttack
        local addAttack = 0.5*realAttack
        local newAttack = realAttack + addAttack       

        hattribute.set(u,0,{attack_white  = "="..newAttack})
        hattribute.set(u,0,{attackAdd1  = "="..addAttack})
    end
})