--- Generated by h-lua-sdk(https://github.com/hunzsig-warcraft3/h-lua-sdk)
ATTR_CONFIGURATOR({
    {"attackAdd1","动态增加攻击力",0},
    {"rectSpawn","区域",1},

})

hslk_unit({
    _parent = "hpea",
    _attr = _attr({
        attack_white = "=100",
        life = "=5000"
    }),
    Name = "天选勇者",
})

hslk_unit({
    _parent = "hpea",
    _attr = _attr({
        rectSpawn = "=1"
    }),
    Name = "小怪",
})