--- Generated by h-lua(https://github.com/h-lua/h-lua)

require "h-lua" -- h-lua库
require "scripts.alias" -- alias h-lua库别称（参考）
require "scripts.setup" -- setup 游戏准备
require "scripts.japi" -- japi
require "scripts.ui" -- UI

-- h-lua main function 主函数入口
-- The game starts here 游戏从main函数开始运行
function main()

    SETUP()
    UI()

    hjapi.DzLoadToc("UI\\frame.toc")

    local bg = hjapi.FrameTag("BACKDROP", "HZ_BACKDROP", hjapi.DzGetGameUI())
    print(bg)
    hjapi.FrameRelation(bg, FRAME_ALIGN_CENTER, hjapi.DzGetGameUI(), FRAME_ALIGN_CENTER, 0, 0)
    hjapi.DzFrameSetTexture(bg, "ReplaceableTextures\\TeamColor\\TeamColor12.blp", 0)
    hjapi.DzFrameSetSize(bg, 0.1, 0.13)
    hjapi.DzFrameShow(bg, false)

    local txt = hjapi.FrameTag("TEXT", "HZ_TEXT", bg)
    hjapi.FrameRelation(txt, FRAME_ALIGN_CENTER, bg, FRAME_ALIGN_CENTER, 0, 0)
    hjapi.DzFrameSetText(txt, "你好世界")
    print(txt)

    local btn = hjapi.FrameTag("BUTTON", "HZ_BUTTON", bg)
    hjapi.FrameRelation(btn, FRAME_ALIGN_CENTER, bg, FRAME_ALIGN_CENTER, 0, 0)
    hjapi.DzFrameSetSize(btn, 0.1, 0.13)
    print(btn)

    hjapi.HzClick(btn, "hello", function()
        print(htime.inc .. ": hello")
    end)
    hjapi.HzClick(btn, "world", function()
        print(htime.inc .. ": world")
    end)
    hjapi.DzFrameShow(bg, true)

    -- 10秒后废弃点击
    htime.setTimeout(10, function()
        print("点击GG")
        hjapi.HzClick(btn, "hello", nil)
        hjapi.DzFrameSetTexture(bg, "ReplaceableTextures\\TeamColor\\TeamColor09.blp", 0)
        hjapi.DzFrameSetAlpha(bg, 200)
        hjapi.DzFrameSetText(txt, "世界")
    end)

end